server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://106.12.168.9:3306/eap_test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: Idea@1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.yjc.entity
